const { Client, GatewayIntentBits, Collection } = require('discord.js');
const { token } = require('./config.json');
const commandHandler = require('./handlers/commandhandler');
const eventHandler = require('./handlers/eventhandler');
const { DisTube } = require('distube'); //
const { SpotifyPlugin } = require('@distube/spotify');
const { SoundCloudPlugin } = require('@distube/soundcloud');
const { YtDlpPlugin } = require('@distube/yt-dlp');
const deployCommands = require('./deployOG.js');
const DistubeEvents = require('./DistubeEvents.js');

deployCommands();
const client = new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildVoiceStates,
    GatewayIntentBits.GuildMembers,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.MessageContent,
    // Add more intents as needed
  ],
});
client.commands = new Collection();

commandHandler(client);
eventHandler(client);
//Distube
const pathToFfmpeg = require('./node_modules/ffmpeg-static/');
client.distube = new DisTube(client, {
  emitAddSongWhenCreatingQueue: false,
  youtubeCookie: [
    {
      domain: '.youtube.com',
      expirationDate: 1747164151.567428,
      hostOnly: false,
      httpOnly: false,
      name: '__Secure-1PAPISID',
      path: '/',
      sameSite: 'unspecified',
      secure: true,
      session: false,
      storeId: '0',
      value: 'BP7GHEoXaTARrhOb/AcQ-tCDPFXoCFEDk1',
      id: 1,
    },
    {
      domain: '.youtube.com',
      expirationDate: 1747164151.567218,
      hostOnly: false,
      httpOnly: true,
      name: '__Secure-1PSID',
      path: '/',
      sameSite: 'unspecified',
      secure: true,
      session: false,
      storeId: '0',
      value:
        'g.a000iQj_51g3sS5hGE2ycrKKWdA9RN9Bf_6RHyF3oWWUD6Ll1Z2MURE0W9LZlTI8rD_4WpgBKQACgYKAZgSAQASFQHGX2Mi_DLmRwB5cLam2ulQUel8gRoVAUF8yKqEyKT4ozLnNP3VcKXtuuvA0076',
      id: 2,
    },
    {
      domain: '.youtube.com',
      expirationDate: 1746544497.259717,
      hostOnly: false,
      httpOnly: true,
      name: '__Secure-1PSIDCC',
      path: '/',
      sameSite: 'unspecified',
      secure: true,
      session: false,
      storeId: '0',
      value: 'AKEyXzVeX89j-hmvvCwmuI-sl07vb5-f_eHFPFhbOpKWEEIG5GxKVOOybp9QHQQGrUPNvNjAgwU',
      id: 3,
    },
    {
      domain: '.youtube.com',
      expirationDate: 1746544497.259566,
      hostOnly: false,
      httpOnly: true,
      name: '__Secure-1PSIDTS',
      path: '/',
      sameSite: 'unspecified',
      secure: true,
      session: false,
      storeId: '0',
      value: 'sidts-CjIBLwcBXG65WrnLkAh-Ke9JLVb9E6QUyiP01GSkGui-J64FYwnGA49tZbb2VotG659NghAA',
      id: 4,
    },
    {
      domain: '.youtube.com',
      expirationDate: 1747164151.567454,
      hostOnly: false,
      httpOnly: false,
      name: '__Secure-3PAPISID',
      path: '/',
      sameSite: 'no_restriction',
      secure: true,
      session: false,
      storeId: '0',
      value: 'BP7GHEoXaTARrhOb/AcQ-tCDPFXoCFEDk1',
      id: 5,
    },
    {
      domain: '.youtube.com',
      expirationDate: 1747164151.567266,
      hostOnly: false,
      httpOnly: true,
      name: '__Secure-3PSID',
      path: '/',
      sameSite: 'no_restriction',
      secure: true,
      session: false,
      storeId: '0',
      value:
        'g.a000iQj_51g3sS5hGE2ycrKKWdA9RN9Bf_6RHyF3oWWUD6Ll1Z2MUpebqQLIPq1IiQ1yJsbz_AACgYKATsSAQASFQHGX2Mi2r2Z9arStfe3VPiOFZ-iAxoVAUF8yKoXLZSiKGZwmTSrGScdIdzD0076',
      id: 6,
    },
    {
      domain: '.youtube.com',
      expirationDate: 1746544497.259744,
      hostOnly: false,
      httpOnly: true,
      name: '__Secure-3PSIDCC',
      path: '/',
      sameSite: 'no_restriction',
      secure: true,
      session: false,
      storeId: '0',
      value: 'AKEyXzXxwTz8EPy2l0iY_43dUFrc98jOzKSXPlwiVFZWWKbAc1X-P7aAWif2vgLHfi_7JfIY2FU',
      id: 7,
    },
    {
      domain: '.youtube.com',
      expirationDate: 1746544497.259654,
      hostOnly: false,
      httpOnly: true,
      name: '__Secure-3PSIDTS',
      path: '/',
      sameSite: 'no_restriction',
      secure: true,
      session: false,
      storeId: '0',
      value: 'sidts-CjIBLwcBXG65WrnLkAh-Ke9JLVb9E6QUyiP01GSkGui-J64FYwnGA49tZbb2VotG659NghAA',
      id: 8,
    },
    {
      domain: '.youtube.com',
      expirationDate: 1740928500.042192,
      hostOnly: false,
      httpOnly: true,
      name: '__Secure-YEC',
      path: '/',
      sameSite: 'lax',
      secure: true,
      session: false,
      storeId: '0',
      value: 'CgttMWxnc1pDZWxPbyiIhNixBjIOCgJCRxIIEgQSAgsMIFg%3D',
      id: 9,
    },
    {
      domain: '.youtube.com',
      expirationDate: 1747164151.56737,
      hostOnly: false,
      httpOnly: false,
      name: 'APISID',
      path: '/',
      sameSite: 'unspecified',
      secure: false,
      session: false,
      storeId: '0',
      value: 'vu3IfOTXzhOM2llF/AOlgj5be6K3wKDLmN',
      id: 10,
    },
    {
      domain: '.youtube.com',
      expirationDate: 1738178957.288264,
      hostOnly: false,
      httpOnly: false,
      name: 'CONSENT',
      path: '/',
      sameSite: 'unspecified',
      secure: true,
      session: false,
      storeId: '0',
      value: 'PENDING+016',
      id: 11,
    },
    {
      domain: '.youtube.com',
      expirationDate: 1747164151.567305,
      hostOnly: false,
      httpOnly: true,
      name: 'HSID',
      path: '/',
      sameSite: 'unspecified',
      secure: false,
      session: false,
      storeId: '0',
      value: 'A5squtk4pxRzOMsX9',
      id: 12,
    },
    {
      domain: '.youtube.com',
      expirationDate: 1747017246.298765,
      hostOnly: false,
      httpOnly: true,
      name: 'LOGIN_INFO',
      path: '/',
      sameSite: 'no_restriction',
      secure: true,
      session: false,
      storeId: '0',
      value:
        'AFmmF2swRQIgFGAR--u318H4z5_Rl9vbYGcOBgDIZVToqyKYOcmc4LYCIQDwL2sAGIN9ld0kHDd2aaaDq9eaDAMGj1wM_TXMO4ukfg:QUQ3MjNmenV3eUFBbmxaVDRJcWFQTWgwT3ZSdTZIMG1FbUpXQ09qNGtUWG9QdXRvREdkUXpPX09GcE01cndjSVpSYUEwSXpfdVd6Rllablp6ZEFiYS14NjhLWFRwNHllQ0FHc0RQNXQ2dXR2U2ZkaF9wYndRazJ0X3hBa1Fza2VxbFBTbmxleXl4Zm4zNkRhUTA3U1VsS3FuQ2lIZmZBTEVMZEhyZDU4bkZnb3UwTTI5bV84NV9QTWlBcmZBWEVzS1kxM2FtaWg0YlpLT2F3UWc5QU4yN1RWbndtQ1IzMnlqZw==',
      id: 13,
    },
    {
      domain: '.youtube.com',
      expirationDate: 1749565872.428736,
      hostOnly: false,
      httpOnly: false,
      name: 'PREF',
      path: '/',
      sameSite: 'unspecified',
      secure: true,
      session: false,
      storeId: '0',
      value: 'f6=400&f7=4150&hl=en&tz=Europe.Sofia&autoplay=true&f5=30000',
      id: 14,
    },
    {
      domain: '.youtube.com',
      expirationDate: 1747164151.567395,
      hostOnly: false,
      httpOnly: false,
      name: 'SAPISID',
      path: '/',
      sameSite: 'unspecified',
      secure: true,
      session: false,
      storeId: '0',
      value: 'BP7GHEoXaTARrhOb/AcQ-tCDPFXoCFEDk1',
      id: 15,
    },
    {
      domain: '.youtube.com',
      expirationDate: 1747164151.567028,
      hostOnly: false,
      httpOnly: false,
      name: 'SID',
      path: '/',
      sameSite: 'unspecified',
      secure: false,
      session: false,
      storeId: '0',
      value:
        'g.a000iQj_51g3sS5hGE2ycrKKWdA9RN9Bf_6RHyF3oWWUD6Ll1Z2Mp3zMs9-nRZpO4_1B_Dv28gACgYKAfESAQASFQHGX2MibqFY_O0KP2kRWjm0M6VDWhoVAUF8yKpIKn23pIbQJ_k6by4pnQ_v0076',
      id: 16,
    },
    {
      domain: '.youtube.com',
      expirationDate: 1746544497.259686,
      hostOnly: false,
      httpOnly: false,
      name: 'SIDCC',
      path: '/',
      sameSite: 'unspecified',
      secure: false,
      session: false,
      storeId: '0',
      value: 'AKEyXzU1JKMO9MEQuyM0OmvsJKiY6c2h6K2ArBPxLHPSGcWijqXIrmPvZA9fTLJbyRxcp-dL2Vba',
      id: 17,
    },
    {
      domain: '.youtube.com',
      expirationDate: 1747164151.567344,
      hostOnly: false,
      httpOnly: true,
      name: 'SSID',
      path: '/',
      sameSite: 'unspecified',
      secure: true,
      session: false,
      storeId: '0',
      value: 'Aq5Sk_PsUxQLLZNir',
      id: 18,
    },
    {
      domain: '.youtube.com',
      expirationDate: 1728868012.537839,
      hostOnly: false,
      httpOnly: true,
      name: 'VISITOR_PRIVACY_METADATA',
      path: '/',
      sameSite: 'no_restriction',
      secure: true,
      session: false,
      storeId: '0',
      value: 'CgJCRxIIEgQSAgsMIBY%3D',
      id: 19,
    },
    {
      domain: '.youtube.com',
      hostOnly: false,
      httpOnly: false,
      name: 'wide',
      path: '/',
      sameSite: 'unspecified',
      secure: false,
      session: true,
      storeId: '0',
      value: '1',
      id: 20,
    },
  ],

  leaveOnEmpty: true,
  ffmpeg: {
    path: pathToFfmpeg,
  },
  leaveOnStop: false,
  nsfw: true,
  plugins: [new SpotifyPlugin(), new SoundCloudPlugin(), new YtDlpPlugin()],
});
module.exports = client; //END OF DISTUBE
DistubeEvents(client);
client.login(token); //musictest token
