const {Client, GatewayIntentBits, Collection} = require('discord.js');
const {token} = require('./config.json');
const commandHandler = require('./handlers/commandhandler');
const eventHandler = require('./handlers/eventhandler');
const {DisTube} = require('distube'); //
const {SpotifyPlugin} = require('@distube/spotify');
const {SoundCloudPlugin} = require('@distube/soundcloud');
const {YtDlpPlugin} = require('@distube/yt-dlp');
const deployCommands = require('./deployOG.js');
const DistubeEvents = require('./DistubeEvents.js');

deployCommands();
const client = new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildVoiceStates,
    GatewayIntentBits.GuildMembers,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.MessageContent,
    // Add more intents as needed
  ],
});
client.commands = new Collection();

commandHandler(client);
eventHandler(client);
//Distube

client.distube = new DisTube(client, {
  emitAddSongWhenCreatingQueue: false,
  youtubeCookie: [
    {
      domain: '.youtube.com',
      expirationDate: 1734135325.360173,
      hostOnly: false,
      httpOnly: true,
      name: '__Secure-1PSIDTS',
      path: '/',
      sameSite: 'unspecified',
      secure: true,
      session: false,
      storeId: '0',
      value: 'sidts-CjIBPVxjSndu6Mwx4gltezzvqA05bFfWuYZN3XFepyr_HEhDbxsAfVM3a3eE_pR92W-IARAA',
      id: 1,
    },
    {
      domain: '.youtube.com',
      expirationDate: 1736710682.185027,
      hostOnly: false,
      httpOnly: false,
      name: '__Secure-3PAPISID',
      path: '/',
      sameSite: 'no_restriction',
      secure: true,
      session: false,
      storeId: '0',
      value: 'aAuLJ9MWRaaerCRL/A1ci_JFNEPkYTc_em',
      id: 2,
    },
    {
      domain: '.youtube.com',
      expirationDate: 1736710682.185057,
      hostOnly: false,
      httpOnly: true,
      name: '__Secure-3PSID',
      path: '/',
      sameSite: 'no_restriction',
      secure: true,
      session: false,
      storeId: '0',
      value: 'dAj_58AhrLythPOMFnjFkMk7UMfTftlS_na9OiwkuWjfHDVpVIvLVlI0QX8ZQWvm5ln8VA.',
      id: 3,
    },
    {
      domain: '.youtube.com',
      expirationDate: 1734138010.665426,
      hostOnly: false,
      httpOnly: true,
      name: '__Secure-3PSIDCC',
      path: '/',
      sameSite: 'no_restriction',
      secure: true,
      session: false,
      storeId: '0',
      value: 'ACA-OxPtf1X5-4woURXnWrFzOzfoOL78355T4p7iMVJhx7pkFWhWXWX7B5WddFlrneJ6zNytUHl7',
      id: 4,
    },
    {
      domain: '.youtube.com',
      expirationDate: 1734135325.360295,
      hostOnly: false,
      httpOnly: true,
      name: '__Secure-3PSIDTS',
      path: '/',
      sameSite: 'no_restriction',
      secure: true,
      session: false,
      storeId: '0',
      value: 'sidts-CjIBPVxjSndu6Mwx4gltezzvqA05bFfWuYZN3XFepyr_HEhDbxsAfVM3a3eE_pR92W-IARAA',
      id: 5,
    },
    {
      domain: '.youtube.com',
      expirationDate: 1703184994.939764,
      hostOnly: false,
      httpOnly: true,
      name: '__Secure-YEC',
      path: '/',
      sameSite: 'lax',
      secure: true,
      session: false,
      storeId: '0',
      value: 'CgtiSnlQa3cyVC1qRSjAws6lBg%3D%3D',
      id: 6,
    },
    {
      domain: '.youtube.com',
      expirationDate: 1703616996.037729,
      hostOnly: false,
      httpOnly: false,
      name: 'CONSENT',
      path: '/',
      sameSite: 'unspecified',
      secure: true,
      session: false,
      storeId: '0',
      value: 'PENDING+525',
      id: 7,
    },
    {
      domain: '.youtube.com',
      expirationDate: 1736791316.523426,
      hostOnly: false,
      httpOnly: true,
      name: 'LOGIN_INFO',
      path: '/',
      sameSite: 'no_restriction',
      secure: true,
      session: false,
      storeId: '0',
      value:
        'AFmmF2swRgIhANRxeTuDv9Do6qPei8m5PlMBKaGWVhQGZMQo3z7e-xvUAiEA5jjtq6bA9OJ0Tm9PUYrxzFWKUgxHfmcEOJzOdEpOZU0:QUQ3MjNmeTdCd2FoOWZRcFh0U3JwT2hQUFdUVmRGN2hDUmhhOWJfU19xcHAtdmVMb3d6eWctUG91UV9WSy1TdVpMcUdGbXJTM2tNNWs4dWloODd5bzFfRk0xM1VRZGo2V3ROX2V3c1ZwWHhHLUx1VFZWQWw1dWhWZS01SHV3UkxtM0ZObEFUdmlzc0NXMHF3dDRxeC1fc01ET0NjbW9wejR4UmdOY095WFlzZ1hHc0RRMVBudE0zOVJsVmV2ZDFVdmxVN2gxdmprTU82cUhFWElONVpSdk5BLXdtX0x3bjZjQQ==',
      id: 8,
    },
    {
      domain: '.youtube.com',
      expirationDate: 1737162006.270643,
      hostOnly: false,
      httpOnly: false,
      name: 'PREF',
      path: '/',
      sameSite: 'unspecified',
      secure: true,
      session: false,
      storeId: '0',
      value: 'tz=Europe.Sofia&f6=400&hl=en&f5=30000&f7=150&autoplay=true',
      id: 9,
    },
    {
      domain: '.youtube.com',
      expirationDate: 1718134419.574151,
      hostOnly: false,
      httpOnly: true,
      name: 'VISITOR_INFO1_LIVE',
      path: '/',
      sameSite: 'no_restriction',
      secure: true,
      session: false,
      storeId: '0',
      value: 'y_KhdvyKXz4',
      id: 10,
    },
    {
      domain: '.youtube.com',
      expirationDate: 1717986723.501638,
      hostOnly: false,
      httpOnly: true,
      name: 'VISITOR_PRIVACY_METADATA',
      path: '/',
      sameSite: 'lax',
      secure: true,
      session: false,
      storeId: '0',
      value: 'CgJCRxIEEgAgaA%3D%3D',
      id: 11,
    },
    {
      domain: '.youtube.com',
      hostOnly: false,
      httpOnly: false,
      name: 'wide',
      path: '/',
      sameSite: 'unspecified',
      secure: false,
      session: true,
      storeId: '0',
      value: '1',
      id: 12,
    },
    {
      domain: '.youtube.com',
      hostOnly: false,
      httpOnly: true,
      name: 'YSC',
      path: '/',
      sameSite: 'no_restriction',
      secure: true,
      session: true,
      storeId: '0',
      value: 'YlbWv6O8ev4',
      id: 13,
    },
  ],

  leaveOnEmpty: true,
  leaveOnStop: false,
  nsfw: true,
  plugins: [new SpotifyPlugin(), new SoundCloudPlugin(), new YtDlpPlugin()],
});
module.exports = client; //END OF DISTUBE
DistubeEvents(client);
client.login(token); //musictest token
